// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class TieContent {
    "TotalContent": string[];
    "Title": string;
    "Author": string;

    /** Creates a new TieContent instance. */
    constructor($$source: Partial<TieContent> = {}) {
        if (!("TotalContent" in $$source)) {
            this["TotalContent"] = [];
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Author" in $$source)) {
            this["Author"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TieContent instance from a string or object.
     */
    static createFrom($$source: any = {}): TieContent {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("TotalContent" in $$parsedSource) {
            $$parsedSource["TotalContent"] = $$createField0_0($$parsedSource["TotalContent"]);
        }
        return new TieContent($$parsedSource as Partial<TieContent>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
