// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tieba$0 from "./tieba/models.js";

export function CreateAiCover(keyword: string, chapterIndex: number): $CancellablePromise<[string, string]> {
    return $Call.ByID(2677229814, keyword, chapterIndex);
}

export function GetConfig(key: string): $CancellablePromise<string> {
    return $Call.ByID(4244716749, key);
}

export function GetTieData(): $CancellablePromise<[boolean, tieba$0.TieContent]> {
    return $Call.ByID(41414847).then(($result: any) => {
        $result[1] = $$createType0($result[1]);
        return $result;
    });
}

export function OnReady(): $CancellablePromise<void> {
    return $Call.ByID(4091821535);
}

export function SaveEPUB(enableCover: boolean): $CancellablePromise<boolean> {
    return $Call.ByID(4202241294, enableCover);
}

export function SetConfig(key: string, value: string): $CancellablePromise<boolean> {
    return $Call.ByID(1844501753, key, value);
}

export function StartDownload(url: string, minimumWord: number, onlyLZ: boolean, filterLink: boolean, filterImg: boolean): $CancellablePromise<void> {
    return $Call.ByID(4028004979, url, minimumWord, onlyLZ, filterLink, filterImg);
}

// Private type creation functions
const $$createType0 = tieba$0.TieContent.createFrom;
